const mapBreedFromBackend = (backendBreed) => {
    const breedMappings = {
        "ABYSSINIAN": "Abyssinian",
        "AEGEAN_CAT": "Aegean cat",
        "AMERICAN_BOBTAIL": "American Bobtail",
        "AMERICAN_CURL": "American Curl",
        "AMERICAN_SHORTHAIR": "American Shorthair",
        "AMERICAN_WIREHAIR": "American Wirehair",
        "ARABIAN_MAU": "Arabian Mau",
        "ASIAN_CAT": "Asian cat",
        "AUSTRALIAN_MIST": "Australian Mist",
        "BALINESE_CAT": "Balinese cat",
        "BENGAL_CAT": "Bengal cat",
        "BIRMAN": "Birman",
        "BOHEMIAN_REX": "Bohemian Rex",
        "BOMBAY_CAT": "Bombay cat",
        "BRAZILIAN_SHORTHAIR": "Brazilian Shorthair",
        "BRITISH_LONGHAIR": "British Longhair",
        "BRITISH_SHORTHAIR": "British Shorthair",
        "BURMESE_CAT": "Burmese cat",
        "BURMILLA": "Burmilla",
        "CALIFORNIA_SPANGLED": "California Spangled",
        "CASHMERE_CAT": "Cashmere cat",
        "CHANTILLY_TIFFANY": "Chantilly Tiffany",
        "CHARTREUX": "Chartreux",
        "CHAUSIE": "Chausie",
        "COLORPOINT_SHORTHAIR": "Colorpoint Shorthair",
        "CORNISH_REX": "Cornish Rex",
        "CYMRIC_CAT": "Cymric cat",
        "CYPRUS_CAT": "Cyprus cat",
        "DEVON_REX": "Devon Rex",
        "DOMESTIC_CAT": "Domestic Cat",
        "DONSKOY_CAT": "Donskoy cat",
        "DRAGON_LI": "Dragon Li",
        "EGYPTIAN_MAU": "Egyptian Mau",
        "EUROPEAN_SHORTHAIR": "European Shorthair",
        "EXOTIC_SHORTHAIR": "Exotic Shorthair",
        "FOLDEX_CAT": "Foldex cat",
        "FOREIGN_WHITE": "Foreign White",
        "GERMAN_REX": "German Rex",
        "HAVANA_BROWN": "Havana Brown",
        "HIGHLANDER_CAT": "Highlander cat",
        "HIMALAYAN_CAT": "Himalayan cat",
        "ISLE_OF_MAN_LONGHAIR_CAT": "Isle of Man Longhair cat",
        "ISLE_OF_MAN_SHORTHAIR_CAT": "Isle of Man Shorthair cat",
        "JAPANESE_BOBTAIL": "Japanese Bobtail",
        "JAVANESE_CAT": "Javanese cat",
        "KANAANI_CAT": "Kanaani cat",
        "KARELIAN_BOBTAIL": "Karelian Bobtail",
        "KHAO_MANEE": "Khao Manee",
        "KORAT": "Korat",
        "KORN_JA": "Korn Ja",
        "KURILIAN_BOBTAIL": "Kurilian Bobtail",
        "LAPERM": "LaPerm",
        "LYKOI": "Lykoi",
        "MAINE_COON": "Maine Coon",
        "MANX_CAT": "Manx cat",
        "MEKONG_BOBTAIL": "Mekong Bobtail",
        "MEXICAN_HAIRLESS_CAT": "Mexican Hairless Cat",
        "MINSKIN": "Minskin",
        "MINUET_CAT": "Minuet cat",
        "MUNCHKIN_CAT": "Munchkin cat",
        "NEBELUNG": "Nebelung",
        "OCICAT": "Ocicat",
        "OJOS_AZULES": "Ojos Azules",
        "ORIENTAL_BICOLOUR": "Oriental Bicolour",
        "ORIENTAL_LONGHAIR": "Oriental Longhair",
        "ORIENTAL_SHORTHAIR": "Oriental Shorthair",
        "PERSIAN_CAT": "Persian cat",
        "PETERBALD": "Peterbald",
        "PITTSBURGH_REFRIGERATOR_CAT": "Pittsburgh refrigerator cat",
        "PIXIE_BOB": "Pixie Bob",
        "RAGAMUFFIN_CAT": "Ragamuffin cat",
        "RAGDOLL": "Ragdoll",
        "RUSSIAN_BLUE": "Russian Blue",
        "RUSSIAN_WHITE": "Russian White",
        "SAVANNAH_CAT": "Savannah cat",
        "SCOTTISH_FOLD": "Scottish Fold",
        "SELKIRK_REX": "Selkirk Rex",
        "SERENGETI_CAT": "Serengeti cat",
        "SIAMESE_CAT": "Siamese cat",
        "NEVA_MASQUERADE": "Neva Masquerade",
        "SIBERIAN_CAT": "Siberian cat",
        "SINGAPURA_CAT": "Singapura cat",
        "SNOWSHOE_CAT": "Snowshoe cat",
        "SOKOKE": "Sokoke",
        "SOMALI_CAT": "Somali cat",
        "SPHYNX_CAT": "Sphynx cat",
        "SUPHALAK": "Suphalak",
        "THAI_CAT": "Thai cat",
        "THAI_LILAC": "Thai Lilac",
        "TIFFANIE_CAT": "Tiffanie cat",
        "TONKINESE_CAT": "Tonkinese cat",
        "TOYBOB": "Toybob",
        "TOYGER": "Toyger",
        "TRADITIONAL_PERSIAN": "Traditional Persian",
        "TRADITIONAL_SIAMESE_CAT": "Traditional Siamese cat",
        "TURKISH_ANGORA": "Turkish Angora",
        "TURKISH_VAN": "Turkish Van",
        "UKRAINIAN_LEVKOY": "Ukrainian Levkoy",
        "YORK_CHOCOLATE": "York Chocolate"
    };

    return breedMappings[backendBreed] || backendBreed;
};

export { mapBreedFromBackend };
